import type { Barber, Look, Service } from "./types";

export const SERVICES: Service[] = [
  {
    id: "srv_signature",
    slug: "corte-assinatura",
    name: "Corte assinatura",
    description: "Leitura de rosto, desenho personalizado e finalização para a sua rotina.",
    durationMinutes: 50,
    priceCents: 7900,
    active: true,
  },
  {
    id: "srv_combo",
    slug: "corte-barba",
    name: "Corte + barba",
    description: "Experiência completa: corte, toalha quente, barba e acabamento de precisão.",
    durationMinutes: 90,
    priceCents: 12900,
    active: true,
  },
  {
    id: "srv_fade",
    slug: "fade-precision",
    name: "Fade precision",
    description: "Degradê construído por camadas, com transição limpa e contorno natural.",
    durationMinutes: 60,
    priceCents: 8900,
    active: true,
  },
  {
    id: "srv_beard",
    slug: "ritual-de-barba",
    name: "Ritual de barba",
    description: "Toalha quente, desenho, navalha e hidratação para pele e fios.",
    durationMinutes: 45,
    priceCents: 6900,
    active: true,
  },
  {
    id: "srv_texture",
    slug: "textura-e-forma",
    name: "Textura & forma",
    description: "Tesoura, movimento e styling para cabelos médios, longos ou cacheados.",
    durationMinutes: 60,
    priceCents: 9900,
    active: true,
  },
  {
    id: "srv_finish",
    slug: "acabamento",
    name: "Acabamento",
    description: "Contorno, nuca, costeletas e styling para manter o desenho entre cortes.",
    durationMinutes: 25,
    priceCents: 4500,
    active: true,
  },
];

export const BARBERS: Barber[] = [
  {
    id: "brb_theo",
    slug: "theo-valente",
    name: "Théo Valente",
    bio: "Obcecado por transições silenciosas e cortes que envelhecem bem. Seu trabalho mistura precisão técnica e leitura de imagem.",
    specialty: "Fade arquitetônico · textura",
    photoUrl: "https://images.unsplash.com/photo-1668596029671-69efaaae388e?auto=format&fit=crop&w=1200&q=86",
    yearsExperience: 9,
    favoriteStyles: "Skin fade, crop francês, textura natural",
    workDays: [2, 4, 6],
    rating: 4.9,
    active: true,
    availability: "Ter, qui e sáb",
  },
  {
    id: "brb_caio",
    slug: "caio-montenegro",
    name: "Caio Montenegro",
    bio: "Especialista no encontro entre alfaiataria e barbearia clássica. Linhas limpas, barba esculpida e conversa sem pressa.",
    specialty: "Clássicos · barba",
    photoUrl: "https://images.unsplash.com/photo-1641129915760-fd8da7097d7c?auto=format&fit=crop&w=1200&q=86",
    yearsExperience: 12,
    favoriteStyles: "Side part, slick back, barba cheia",
    workDays: [3, 4, 5, 6],
    rating: 5,
    active: true,
    availability: "Qua, qui, sex e sáb",
  },
  {
    id: "brb_rafa",
    slug: "rafael-dias",
    name: "Rafael Dias",
    bio: "Pesquisa comportamento, rua e música para criar cortes atuais sem prazo de validade. Forte em tesoura e cabelos cacheados.",
    specialty: "Modernos · cacheados",
    photoUrl: "https://images.unsplash.com/photo-1741345980762-9eb594e6fd31?auto=format&fit=crop&w=1200&q=86",
    yearsExperience: 7,
    favoriteStyles: "Mullet, curly crop, burst fade",
    workDays: [2, 3, 5, 6],
    rating: 4.8,
    active: true,
    availability: "Ter, qua, sex e sáb",
  },
];

export const LOOKS: Look[] = [
  {
    id: "look_01",
    category: "Fade",
    name: "Low fade / 01",
    description: "Base baixa, peso preservado no topo e acabamento fosco. Crescimento bonito por até três semanas.",
    imageUrl: "https://images.unsplash.com/photo-1692726485953-5138cee215fe?auto=format&fit=crop&w=1400&q=88",
    imageAlt: "Corte masculino low fade com acabamento preciso",
    serviceSlug: "fade-precision",
    barberId: "brb_theo",
  },
  {
    id: "look_02",
    category: "Classic",
    name: "Gentleman / 02",
    description: "Laterais clássicas, divisão suave e brilho controlado. Um corte formal sem rigidez.",
    imageUrl: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1400&q=88",
    imageAlt: "Corte clássico masculino em ambiente de barbearia",
    serviceSlug: "corte-assinatura",
    barberId: "brb_caio",
  },
  {
    id: "look_03",
    category: "Beard",
    name: "Outline / 03",
    description: "Volume preservado, linha de bochecha natural e pescoço limpo para uma barba mais densa.",
    imageUrl: "https://images.unsplash.com/photo-1523532931495-f51ebf4bc3a2?auto=format&fit=crop&w=1400&q=88",
    imageAlt: "Barba masculina sendo desenhada por barbeiro",
    serviceSlug: "ritual-de-barba",
    barberId: "brb_caio",
  },
  {
    id: "look_04",
    category: "Texture",
    name: "Rough texture / 04",
    description: "Movimento criado com tesoura e produto leve. Funciona arrumado ou propositalmente imperfeito.",
    imageUrl: "https://images.unsplash.com/photo-1759134155377-4207d89b39ec?auto=format&fit=crop&w=1400&q=88",
    imageAlt: "Corte masculino texturizado contemporâneo",
    serviceSlug: "textura-e-forma",
    barberId: "brb_rafa",
  },
  {
    id: "look_05",
    category: "Modern",
    name: "Street crop / 05",
    description: "Franja curta, laterais compactas e textura alta: desenho urbano com manutenção simples.",
    imageUrl: "https://images.unsplash.com/photo-1782596747899-e522836b328e?auto=format&fit=crop&w=1400&q=88",
    imageAlt: "Corte masculino moderno com franja curta",
    serviceSlug: "corte-assinatura",
    barberId: "brb_rafa",
  },
  {
    id: "look_06",
    category: "Fade",
    name: "High contrast / 06",
    description: "Contraste alto, contorno limpo e topo definido para uma silhueta mais gráfica.",
    imageUrl: "https://images.unsplash.com/photo-1759142016096-a9d1a5ebcc09?auto=format&fit=crop&w=1400&q=88",
    imageAlt: "Corte fade de alto contraste em close",
    serviceSlug: "fade-precision",
    barberId: "brb_theo",
  },
];

export function formatMoney(cents: number): string {
  return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100);
}
